spring:
  application:
    name: games-telegram-bot
  main:
    web-application-type: none
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/games_bot}
    username: ${DB_USERNAME:games_bot}
    password: ${DB_PASSWORD:games_bot_local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: games_bot
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
